<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>https://github.com/ViniciusMoraisAraujo/CadeMeuPet/pull/6/conflict?name=src%252FCadeMeuPet.Application%252FCadeMeuPet.Application.csproj&base_oid=93e974eaf4c2f8e0fdd60423cf70e0f29c7e7196&head_oid=91bf44f0a4ea959c60c55cc08151f91ce80f1f72
    <ProjectReference Include="..\CadeMeuPet.Domain\CadeMeuPet.Domain.csproj" />
  </ItemGroup>
</Project>
